### PR TITLE
Fix issue #151:Unify B->pilnu and B->Dlnu code, add B_s->Klnu

### LINKED ISSUE #151: B->pilnu::BR does not yet support l=tau
Svjetlana and Blazenka would like to use this.

### PR DESCRIPTION
**Pull request by dvandyk**
When this is complete, it should fix #151.

@akokulu7, @cBobeth can you guys take over from here?

Still missing:
- [ ] all test cases for ```B_s->K```
- [ ] NP test cases for ```B->pi```
- [ ] ```l=tau``` test cases for ```B->pi```

### CODE REVIEW

**Comment by dvandyk** [comment]
@cBobeth, @akokulu7 seems that some of the examples in ```manual/examples``` use q2 smaller than m_mu^2. Might be a good idea to ensure the differential rate yields zero outside the physical phase space!

**Comment by dvandyk** [comment]
@cBobeth any chance we get this in before the end of July?

**Comment by cBobeth** [comment]
I am sorry, but to do this I should write some independent code (Mathematica or a-like) to generate the numbers for the test cases.

File: eos/utils/standard-model.cc [hunk 1]
```diff
@@ -429,6 +430,78 @@ namespace implementation
...
+                return QCD::m_q_msbar(m_d_0, alpha_s_mu0, alpha_s(mu), QCD::beta_function_nf_4, QCD::gamma_m_nf_4);
+
+            double alpha_s_b = alpha_s(_mu_b__qcd);
+            m_d_0 = QCD::m_q_msbar(m_d_0, alpha_s_mu0, alpha_s_b, QCD::beta_function_nf_4, QCD::gamma_m_nf_4);
+            alpha_s_mu0 = alpha_s_b;
+
+            if (mu <= _mu_t__qcd)
+                return QCD::m_q_msbar(m_d_0, alpha_s_mu0, alpha_s(mu), QCD::beta_function_nf_5, QCD::gamma_m_nf_5);
+
+            throw InternalError("SMComponent<components::QCD>::m_d_msbar: Running of m_u_MSbar to mu > mu_t not yet implemented");
```
Comment (cBobeth) [inline eos/utils/standard-model.cc]: m_u_MSbar should be m_d_MSbar

File: eos/utils/standard-model.cc [hunk 2]
```diff
@@ -429,6 +430,78 @@ namespace implementation
...
+                return QCD::m_q_msbar(m_d_0, alpha_s_mu0, alpha_s(mu), QCD::beta_function_nf_4, QCD::gamma_m_nf_4);
+
+            double alpha_s_c = alpha_s(_mu_c__qcd);
+            m_d_0 = QCD::m_q_msbar(m_d_0, alpha_s_mu0, alpha_s_c, QCD::beta_function_nf_4, QCD::gamma_m_nf_4);
+            alpha_s_mu0 = alpha_s_c;
+
+            if (mu >= 1.0)
+                return QCD::m_q_msbar(m_d_0, alpha_s_mu0, alpha_s(mu), QCD::beta_function_nf_3, QCD::gamma_m_nf_3);
+
+            throw InternalError("SMComponent<components::QCD>::m_d_msbar: Running of m_u_MSbar to mu < 1.0 GeV not yet implemented");
```
Comment (cBobeth) [inline eos/utils/standard-model.cc]: see line 487

File: eos/b-decays/b-to-psd-l-nu.hh [hunk 3]
```diff
@@ -58,7 +58,7 @@ namespace eos
             // Integrated Observables - normalized(|Vcb|=1)
             double normalized_integrated_branching_ratio(const double & s_min, const double & s_max) const;
 
-            // R_D
+            // R_P
             double differential_r_d(const double & s) const;
```
Comment (cBobeth) [inline eos/b-decays/b-to-psd-l-nu.hh]: We could rename this from "..._r_d" -> "..._r_P"

File: eos/b-decays/b-to-psd-l-nu.cc [hunk 4]
```diff
@@ -419,7 +515,7 @@ namespace eos
     }
 
     double
-    BToDLeptonNeutrino::differential_r_d(const double & s) const
+    BToPseudoscalarLeptonNeutrino::differential_r_d(const double & s) const
```
Comment (cBobeth) [inline eos/b-decays/b-to-psd-l-nu.cc]: See also comment in header file: rename "..._r_d" -> "..._r_P"

File: eos/b-decays/b-to-psd-l-nu_TEST.cc [hunk 5]
```diff
@@ -0,0 +1,134 @@
...
+                p1["B->D::b_T^2@BCL2008"]   = +0.00;
+                p1["mass::B_d"]             =  5.279;
+                p1["mass::D_d"]             =  1.870;
+                // by default, all other couplings are zero in eos
+                p1["b->cmunumu::Re{cVL}"]   =  1.0;
+
+                Options oo;
+                oo.set("model", "WilsonScan");
+                oo.set("form-factors", "BCL2008");
+                oo.set("q", "d");
```
Comment (cBobeth) [inline eos/b-decays/b-to-psd-l-nu_TEST.cc]: Set also options "U" and "l" to not to rely on current default settings?

File: eos/b-decays/bs-to-kstar-l-nu.cc [hunk 6]
```diff
@@ -605,7 +611,7 @@ namespace eos
     {
         AngularCoefficients a_c = _imp->bstokstarlnu._imp->integrated_angular_coefficients(0.02, 19.71);
 
-        return 4.0 / 9.0 * (2.0 * a_c.j1s + 3.0 * a_c.j3) / _imp->btopilnu.integrated_decay_width(0.02, 12.0);
+        return 4.0 / 9.0 * (2.0 * a_c.j1s + 3.0 * a_c.j3) * _imp->tau() / _imp->hbar() / _imp->btopilnu.integrated_branching_ratio(0.02, 12.0);
```
Comment (cBobeth) [inline eos/b-decays/bs-to-kstar-l-nu.cc]: Please check whether you need to normalize to B -> Pi mu nu only in "ratio_perp" or also in the other two ratios "ratio_para" and "ratio_long". Also seems strange convention to integrate B_s -> K^* mu nu up to 19.71 GeV², but the
 B -> Pi mu nu only up to 12 GeV^2 ?!

File: eos/b-decays/observables.cc [hunk 7]
```diff
@@ -66,16 +65,19 @@ namespace eos
             R"(The option "form-factors" selects the form factor parametrization.)",
             {
                 make_observable("B->pilnu::dBR/dq2", R"(d\mathcal{B}(B\to\pi\ell^-\bar\nu)/dq^2)",
-                        &BToPiLeptonNeutrino::differential_branching_ratio,
-                        std::make_tuple("q2")),
+                        &BToPseudoscalarLeptonNeutrino::differential_branching_ratio,
+                        std::make_tuple("q2"),
+                        Options{ { "U", "u" } }),
```
Comment (cBobeth) [inline eos/b-decays/observables.cc]: Should'nt we fix here also the option "q" = "d" and not rely on the default setting?

File: eos/b-decays/observables.cc [hunk 8]
```diff
@@ -66,16 +65,19 @@ namespace eos
...
 
                 make_observable("B->pilnu::BR", R"(\mathcal{B}(B\to\pi\ell^-\bar\nu))",
-                        &BToPiLeptonNeutrino::integrated_branching_ratio,
-                        std::make_tuple("q2_min", "q2_max")),
+                        &BToPseudoscalarLeptonNeutrino::integrated_branching_ratio,
+                        std::make_tuple("q2_min", "q2_max"),
+                        Options{ { "U", "u" } }),
```
Comment (cBobeth) [inline eos/b-decays/observables.cc]: See line 70

File: eos/b-decays/observables.cc [hunk 9]
```diff
@@ -66,16 +65,19 @@ namespace eos
...
 
                 make_observable("B->pilnu::zeta",
-                        &BToPiLeptonNeutrino::integrated_zeta,
-                        std::make_tuple("q2_min", "q2_max")),
+                        &BToPseudoscalarLeptonNeutrino::normalized_integrated_branching_ratio,
+                        std::make_tuple("q2_min", "q2_max"),
+                        Options{ { "U", "u" } }),
```
Comment (cBobeth) [inline eos/b-decays/observables.cc]: See line 70

File: eos/observable-impl.hh [hunk 10]
```diff
@@ -65,45 +65,49 @@ namespace eos
         }
     };
 
-    /* Helper functions to create ObserableEntry */
+    /* Helper functions to create ObservableEntry */
```
Comment (cBobeth) [inline eos/observable-impl.hh]: Do you want to split off this file as a separate commit -> is independent of B->P l v ?!

File: eos/utils/concrete_observable.hh [hunk 11]
```diff
@@ -127,15 +127,19 @@ namespace eos
 
             std::array<const std::string, sizeof...(Args_)> _kinematics_names_array;
 
+            Options _forced_options;
```
Comment (cBobeth) [inline eos/utils/concrete_observable.hh]: See observable-impl.hh: Do you want to split off this file as a separate commit -> is independent of B->P l v ?!

File: eos/b-decays/b-to-psd-l-nu_TEST.cc (hunk 5 above)
Comment (dvandyk) [reply eos/b-decays/b-to-psd-l-nu_TEST.cc]: We decided anyway to remove this test case, since it duplicates the existing B->Dlnu test case...

File: eos/b-decays/bs-to-kstar-l-nu.cc (hunk 6 above)
Comment (dvandyk) [reply eos/b-decays/bs-to-kstar-l-nu.cc]: That was on purpose for the project, see http://arxiv.org/abs/arXiv:1503.09063

File: eos/b-decays/observables.cc (hunk 7 above)
Comment (dvandyk) [reply eos/b-decays/observables.cc]: Nope, we want the user to be able to set it. The options listed here override any user-provided options.

File: eos/observable-impl.hh (hunk 10 above)
Comment (dvandyk) [reply eos/observable-impl.hh]: Nope :-)

File: eos/utils/concrete_observable.hh (hunk 11 above)
Comment (dvandyk) [reply eos/utils/concrete_observable.hh]: Keep it

**Comment by dvandyk** [comment]
Test cases for B->pi l nu failed since the old values did not account for the Sirlin factor, which was handled by the old B->D l nu code. Fixed that as well.

File: eos/b-decays/b-to-psd-l-nu.hh (hunk 3 above)
Comment (dvandyk) [reply eos/b-decays/b-to-psd-l-nu.hh]: Resolved using ObservableRatio. This code has been removed altogether...

File: eos/b-decays/b-to-psd-l-nu.cc (hunk 4 above)
Comment (dvandyk) [reply eos/b-decays/b-to-psd-l-nu.cc]: Also resolved via ObservableRatio.

**Comment by dvandyk** [comment]
@cBobeth Can you rebase and merge this if the test cases run through?
