### PR TITLE
[utils] Fixes #1045  Treatment of kinematics for ExpressionCacher for ObservableExpression

### LINKED ISSUE #1045: Sampling of newly defined observables created using same type observables not working
If I try to create a new observable from an arithmetic expression and if this 
expression includes at least two times the same type of observable but with different 
kinematics, then the sampling appears to not work as intended.
The direct evaluation of the same observable seems to be correct and gives 
deviating results.

As an example I try to evaluate and sample the form factor f_+(q2) of B->pi
and create new observables by dividing, adding or subtracting the form factor for different kinematic values e.g. "f_+(q2_1) / f_+(q2_2)"

Using the predict method I get:
f_+(0.0) = 2.654e-01 +/- 3.204e-02
f_+(1.5) = 2.857e-01 +/- 3.501e-02
f_+(0.0) / f_+(1.5) = 1.000e+00 +/- 0.000e+00
f_+(0.0) + f_+(1.5) = 5.714e-01 +/- 7.002e-02
f_+(0.0) - f_+(1.5) = 0.000e+00 +/- 0.000e+00

On the other hand using the evaluate method for default values I get:
f_+(0.0) / f_+(1.5) = 0.9263299918881416
f_+(0.0) + f_+(1.5) = 0.6384153732345865
f_+(0.0) - f_+(1.5) = -0.02441537323458659

I use the following .yaml file:

    likelihoods:
      - name: TH-pi
        constraints:
          - "B->pi::form-factors[f_+,f_0,f_T]@LMvD:2021A;form-factors=BCL2008-4"
          - "B->pi::f_++f_0+f_T@FNAL+MILC:2015C;form-factors=BCL2008-4"
          - "B->pi::f_++f_0@RBC+UKQCD:2015A;form-factors=BCL2008-4"
    
    priors:
      - name: FF-pi
        descriptions:
          - {
              "parameter": "B->pi::f_+(0)@BCL2008",
              "min": 0.21,
              "max": 0.32,
              "type": "uniform",
            }
          - {
              "parameter": "B->pi::b_+^1@BCL2008",
              "min": -2.96,
              "max": -0.60,
              "type": "uniform",
            }
          - {
              "parameter": "B->pi::b_+^2@BCL2008",
              "min": -3.98,
              "max": 4.38,
              "type": "uniform",
            }
          - {
              "parameter": "B->pi::b_+^3@BCL2008",
              "min": -18.30,
              "max": 9.27,
              "type": "uniform",
            }
    
    posteriors:
      - name: TEST
        prior:
          - FF-pi
        likelihood:
          - TH-pi
    
    observables:
      "B->pi::f_+(q2_1)/f_+(q2_2)":
        latex: '$\frac{f_+(q^2_1)}{f_+(q^2_2)}$'
        unit: "1"
        options: {}
        expression: "<<B->pi::f_+(q2)>>[q2=>q2_1] / <<B->pi::f_+(q2)>>[q2=>q2_2]"
      "B->pi::f_+(q2_1)+f_+(q2_2)":
        latex: "$f_+(q^2_1)+f_+(q^2_2)$"
        unit: "1"
        options: {}
        expression: "<<B->pi::f_+(q2)>>[q2=>q2_1] + <<B->pi::f_+(q2)>>[q2=>q2_2]"
      "B->pi::f_+(q2_1)-f_+(q2_2)":
        latex: "$f_+(q^2_1)-f_+(q^2_2)$"
        unit: "1"
        options: {}
        expression: "<<B->pi::f_+(q2)>>[q2=>q2_1] - <<B->pi::f_+(q2)>>[q2=>q2_2]"
    
    predictions:
      - name: FFs_divide
        global_options:
          form-factors: BCL2008
          l: mu
        observables:
          - name: B->pi::f_+(q2_1)/f_+(q2_2)
            kinematics:
              q2_1: 0.0
              q2_2: 1.5
      - name: FFs_add
        global_options:
          form-factors: BCL2008
          l: mu
        observables:
          - name: B->pi::f_+(q2_1)+f_+(q2_2)
            kinematics:
              q2_1: 0.0
              q2_2: 1.5
      - name: FFs_subtract
        global_options:
          form-factors: BCL2008
          l: mu
        observables:
          - name: B->pi::f_+(q2_1)-f_+(q2_2)
            kinematics:
              q2_1: 0.0
              q2_2: 1.5
      - name: f+_nom
        global_options:
          form-factors: BCL2008
          l: mu
        observables:
          - name: B->pi::f_+(q2)
            kinematics:
              q2: 0.0
      - name: f+_denom
        global_options:
          form-factors: BCL2008
          l: mu
        observables:
          - name: B->pi::f_+(q2)
            kinematics:
              q2: 1.5
    
and the following .py file for the calculation:

    import eos 
    import numpy as np 

    EOS_BASE_DIRECTORY = "./test_example-data"

    eos.tasks.sample_prior('./test_example.yaml',posterior='TEST',
                       base_directory=EOS_BASE_DIRECTORY, N=1000, seed=42)

    output = eos.data.ImportanceSamples(EOS_BASE_DIRECTORY+'/TEST/samples')
    print(f'shape of output: {output.samples.shape}')

    for obs in ['f+_nom','f+_denom', 'FFs_divide','FFs_add', 'FFs_subtract']:

        eos.tasks.predict_observables('./test_example.yaml', base_directory=EOS_BASE_DIRECTORY, posterior='TEST',
                                  prediction=obs)
    
        prediction = eos.data.Prediction(EOS_BASE_DIRECTORY+'/TEST/pred-'+obs)
        avg = np.average(prediction.samples[:,0],weights=prediction.weights, axis=0)
        std = np.sqrt(np.average((prediction.samples[:,0]-avg)**2, weights=prediction.weights, axis=0))
        print(f'{obs} = {avg:.3e} +/- {std:.3e}')

    parameters = eos.Parameters.Defaults()
    for obs_name in ['B->pi::f_+(q2_1)/f_+(q2_2)','B->pi::f_+(q2_1)+f_+(q2_2)','B->pi::f_+(q2_1)-f_+(q2_2)']:
        obs = eos.Observable.make(obs_name,parameters,eos.Kinematics(q2_1=0.0,q2_2=1.5), eos.Options(l='mu',**{'form-factors':'BCL2008'}))
        print(f'{obs_name} = {obs.evaluate()}')

### PR DESCRIPTION
**Pull request by DominikSue**
Previously `ExpressionCacher` did cache sub-expressions of type `ObservableExpression` with the kinematics of the main expression and without specifying aliases.
I added a new kinematics object with updated values that are necessary to efficiently cache sub-expressions of type `ObservableExpression`

I also extended the if statement for comparing kinematics which is needed for caching as it didn't catch the case where the first element of the alias map is identical but the second is not.

### CODE REVIEW

**Review by dvandyk — CHANGES_REQUESTED** [review]
Thanks @DominikSue, I appreciate your PR very much!

1. I agree with the change to the ``Kinematics::operator==``. However, since it is a separate bugfix, it should probably be in an independent commit (in this branch of course!)
2. I disagree with the solution that you propose; please see me detailed comment and alternative suggestion.
3. I think this (subtle) bug requires a test case so we avoid it returning in the future. Can you turn your example expression into a test case, validating first that the test fails without your fix and does not with your fix applied?

File: eos/utils/kinematic.hh [hunk 1]
```diff
@@ -223,6 +233,68 @@ namespace eos
...
+            void uses_kinematic(const KinematicUser & user);
+            ///@}
+    };
+
+    extern template class WrappedForwardIterator<KinematicUser::ConstIteratorTag, const KinematicVariable::Id>;
+
+    /*!
+     * Wrapper class to automate usage tracking of Kinematics objects.
+     */
+    class UsedKinematicVariable : public KinematicVariable
```
Comment (dvandyk) [inline eos/utils/kinematic.hh:282]: Nice.

File: eos/utils/kinematic.hh [hunk 2]
```diff
@@ -223,6 +233,68 @@ namespace eos
...
+             * Remove a kinematics variable from the set of used ids.
+             */
+            void drop(const KinematicVariable::Id & id);
+
+            /*!
+             * Add a given kinematics variable id to our list of used ids.
+             *
+             * @param id   The kinematics variable id that we use.
+             */
+            void uses_kinematic(const KinematicVariable::Id & id);
```
Comment (dvandyk) [inline eos/utils/kinematic.hh:266]: I think this should be ``uses`` just like for ``ParameterUser``. We can and should select which base class we mean by recasting, right?
```C++
reinterpret_cast<ParameterUser *>(this)->uses(...);
reinterpret_cast<KinematicUser *>(this)->uses(...);
```

File: eos/utils/kinematic.hh [hunk 3]
```diff
@@ -223,6 +233,68 @@ namespace eos
...
+
+            /*!
+             * Copy parameter ids of another KinematicUser to our list of used ids.
+             *
+             * @param user The other ParameterUser whose ids we are going to copy.
+             */
+            void uses_kinematic(const KinematicUser & user);
```
Comment (dvandyk) [inline eos/utils/kinematic.hh:273]: Ditto, see above.

File: eos/utils/expression-visitors.cc [hunk 4]
```diff
@@ -688,8 +689,37 @@ namespace eos::exp
...
+            const auto entry = it->second;
+            kinematic_set.insert(entry->begin_kinematic_variables(), entry->end_kinematic_variables());
+        }
+
+        // add the ids of the used kinematic variables to kinematic_user
+        for (const auto & kinematic_name : kinematic_set)
+        {
+            e.observable->uses_kinematic(e.observable->kinematics()[kinematic_name].id());
+        }
+
```
Comment (dvandyk) [inline eos/utils/expression-visitors.cc:714]: This piece of code is in the wrong place. After your previous commit, all observables must track their own use of kinematic variables. This type of code needs to go into ``ConcreteObservable<T_>``, amongst other things.

Maybe we should have a brief meeting about this? Might be easier and faster?

**Review by dvandyk — APPROVED** [review]
